# Generated by Django 5.1.7 on 2025-05-13 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tuman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Viloyat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Mahalla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('population', models.PositiveIntegerField(default=0)),
                ('houses', models.PositiveIntegerField(default=0)),
                ('tuman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mahallalar', to='mahalla_app.tuman')),
            ],
        ),
        migrations.AddField(
            model_name='tuman',
            name='viloyat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tumanlar', to='mahalla_app.viloyat'),
        ),
    ]
